/**
 * ============================================================================
 * 🔌 TUDOFAZ HUB - SUPABASE CLIENT CONFIGURATION
 * ============================================================================
 * 
 * Supabase client initialization with optimized configuration
 * Handles authentication, database connections, and real-time subscriptions
 * 
 * @author by_arturalves
 * @file client.ts
 * @version 1.0.0
 * @year 2025
 * 
 * Configuration Features:
 * - 🔐 Persistent authentication sessions
 * - 🔄 Automatic token refresh
 * - 💾 Local storage for auth state
 * - 📡 Real-time subscriptions support
 * - 🛡️ Type-safe database operations
 * 
 * Supabase Services Used:
 * - Database (PostgreSQL with RLS)
 * - Authentication (JWT-based)
 * - Real-time (WebSocket subscriptions) 
 * - Storage (File uploads)
 * - Edge Functions (Serverless API)
 * 
 * ============================================================================
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jprmzutdujnufjyvxtss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwcm16dXRkdWpudWZqeXZ4dHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5Mzc0MDMsImV4cCI6MjA3MDUxMzQwM30.oLRzf4v6IJvWuulfoZVwya6T8AUEWmN2pQNs6kZ4Qhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});